<a href="https://colab.research.google.com/github/Bigdata-webtoon-recommendation/webtoon-crawlers/blob/main/csv_integration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import csv
import nltk
from nltk.tokenize import word_tokenize
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer
import operator
import pandas as pd

# 네이버 csv 정리

제목 / 작가 / 평점 / 연령정보(성인orNot) / 장르(g1 - g12) / 키워드  형태로

## 1. 기존의 크롤링 csv에서 그림작가는 제외한 형태로 가공 (crawling_result_naver_clear.csv)

In [4]:
with open('crawling_result_naver.csv', encoding="utf-8") as csv_file:
  with open('crawling_result_naver_clear.csv',mode='w',newline='',encoding='utf-8') as my_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    my_writer = csv.writer(my_file,delimiter=',')
    my_writer.writerow(['idx','name','score','writer','age_limit'])   #,'g1','g2','g3','g4','g5','g6','g7','g8','g9','g10','g11','g12', 'keywords'])

    line_count = 0
    for row in csv_reader:  #csv_reader:
      # #if line_count == 0:
      # #  line_count = line_count + 1 #다음의 경우 헤더있음. 네이버는 이거 주석처리!!
      # if line_count > 10:
      #   break;
        
      # else:
        webtoon_idx = row[0]
        webtoon_name = row[1]
        webtoon_writer = row[2]
        webtoon_score = row[3]
        webtoon_agelimit = row[5]

        if len(webtoon_writer.split(' /')) > 1: 
          webtoon_writer = webtoon_writer.split(' /')[0]
          #print(webtoon_writer)
        
        my_writer.writerow([webtoon_idx, webtoon_name, webtoon_score, webtoon_writer, webtoon_agelimit])
        line_count = line_count +1

## 2. 장르 / 키워드와 합쳐서 최종 csv (naver_complete.csv)

* 아직 키워드를 좀더 가공해서 쓸지 어떻게 할지는 미완!

In [20]:
import pandas as pd
init_data = pd.read_csv('./crawling_result_naver_clear.csv')

genre_data = pd.read_csv('./crawling_genre_tagging_naver_v2.csv')

keyword_data = pd.read_csv('./storykeywords_result_naver.csv')

init_data['g1'] = genre_data['episode']
init_data['g2'] = genre_data['story']
init_data['g3'] = genre_data['daily_life']
init_data['g4'] = genre_data['comic']
init_data['g5'] = genre_data['fantasy']
init_data['g6'] = genre_data['action']
init_data['g7'] = genre_data['drama']
init_data['g8'] = genre_data['romance']
init_data['g9'] = genre_data['thriller']
init_data['g10'] = genre_data['period_drama']
init_data['g11'] = genre_data['sports']
init_data['g12'] = genre_data['campus_life']
init_data['keywords'] = keyword_data['스토리 키워드']

init_data.to_csv('./naver_complete.csv',index=False)
init_data.head()

   idx     name  ...  g12                                           keywords
0    1     인생존망  ...    1                           ['인생', '학교', '내가', '한번']
1    2     독립일기  ...    0                                       ['혼자', '처음']
2    3   모죠의 일지  ...    0                          ['머릿속', '세포', '유미', '생각']
3    4    한림체육관  ...    0              ['소신', '취향', '비밀', '성향', '내성', '내성적']
4    5  유미의 세포들  ...    1  ['한림', '학원', '무도', '체육관', '실천', '영하', '액션물', '...

[5 rows x 18 columns]

# 다음 csv 정리

제목 / 작가 / 평점 / 연령정보(성인orNot) / 장르(g1 - g12) / 키워드  형태로

## 1. 기존의 크롤링 csv에서 clear형태로가공 (crawling_result_daum_clear.csv)

In [32]:
with open('crawling_result_daum.csv', encoding="utf-8") as csv_file:
  with open('crawling_result_daum_clear.csv',mode='w',newline='',encoding='utf-8') as my_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    my_writer = csv.writer(my_file,delimiter=',')
    my_writer.writerow(['idx','name','score','writer','age_limit'])   #,'g1','g2','g3','g4','g5','g6','g7','g8','g9','g10','g11','g12', 'keywords'])

    line_count = 0
    for row in csv_reader:
      if line_count == 0:
       line_count = line_count + 1 #다음의 경우 헤더있음
      # elif line_count > 10:
      #    break;
        
      else:
        idx_int = int(row[0])
        webtoon_idx = idx_int + 1182
        webtoon_name = row[1]
        webtoon_writer = row[2]
        webtoon_score = row[3]
        webtoon_agelimit = row[4]

        if len(webtoon_writer.split("', '")) > 1: 
          webtoon_writer = webtoon_writer.split("', '")[0][2:]
          
        webtoon_score = webtoon_score[0:4]
        my_writer.writerow([webtoon_idx, webtoon_name, webtoon_score, webtoon_writer, webtoon_agelimit])
        line_count = line_count +1

In [ ]:
init_data.last_valid_index

## 2. 장르 / 키워드와 합쳐서 최종 csv (daum_complete.csv)

* 아직 키워드를 좀더 가공해서 쓸지 (다음의 경우 원래 제공되는 키워드를 쓸지) 어떻게 할지는 미완!

In [33]:
init_data2 = pd.read_csv('./crawling_result_daum_clear.csv')

genre_data2 = pd.read_csv('./crawling_genre_tagging_daum_v2.csv')

keyword_data2 = pd.read_csv('./storykeywords_result_daum.csv')

init_data2['g1'] = genre_data2['episode']
init_data2['g2'] = genre_data2['story']
init_data2['g3'] = genre_data2['daily_life']
init_data2['g4'] = genre_data2['comic']
init_data2['g5'] = genre_data2['fantasy']
init_data2['g6'] = genre_data2['action']
init_data2['g7'] = genre_data2['drama']
init_data2['g8'] = genre_data2['romance']
init_data2['g9'] = genre_data2['thriller']
init_data2['g10'] = genre_data2['period_drama']
init_data2['g11'] = genre_data2['sports']
init_data2['g12'] = genre_data2['campus_life']
init_data2['keywords'] = keyword_data2['스토리 키워드']

init_data2.to_csv('./daum_complete.csv',index=False)
init_data2.head()

    idx          name  ...  g12                                       keywords
0  1182     무지개다리 파수꾼  ...    0    ['동물', '한철', '성공', '수의사', '유명', '전부', '소리']
1  1183          서천화원  ...    0        ['공주', '운명', '모험', '좌충우돌', '개척', '로맨스']
2  1184        봄날의 팔광  ...    0  ['로맨스', '달님', '지상', '판타지', '선녀', '싸가지', '최대']
3  1185   뱀파이어님의 대리식사  ...    0              ['대학생', '생활', '동거', '시영', '뱀파이어']
4  1186  현세이의 보이는 라디오  ...    0                       ['일상', '리머', '현세', '소통']

[5 rows x 18 columns]

# 최종 네이버 + 다음 통합 csv (naver_daum_integration.csv)

* idx의 경우 다음웹툰을 네이버웹툰 밑에 순서대로 넣었고 그에 따라 idx는 그냥 증가하게 함!

In [35]:
import pandas as pd
import glob
import os

all_data=[]

naver_data = pd.read_csv('./naver_complete.csv')
all_data.append(naver_data)

daum_data = pd.read_csv('./daum_complete.csv')
all_data.append(daum_data)

combined_data = pd.concat(all_data,axis=0)
combined_data.to_csv('./naver_daum_integration.csv',index=False)

In [36]:
combined_data.head()

   idx     name  ...  g12                                           keywords
0    1     인생존망  ...    1                           ['인생', '학교', '내가', '한번']
1    2     독립일기  ...    0                                       ['혼자', '처음']
2    3   모죠의 일지  ...    0                          ['머릿속', '세포', '유미', '생각']
3    4    한림체육관  ...    0              ['소신', '취향', '비밀', '성향', '내성', '내성적']
4    5  유미의 세포들  ...    1  ['한림', '학원', '무도', '체육관', '실천', '영하', '액션물', '...

[5 rows x 18 columns]